name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  HELM_EXPERIMENTAL_OCI: 1


jobs:

  build_push_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag barclaysacr02.azurecr.io/deeven01:latest
   
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: barclaysacr02 # ${{ secrets.ACR_NAME }}
        # Container registry password
        password: AFnp+BILCUFnV9EuVTr9sxOBt/KqS=yU
        # Container registry server url
        login-server: barclaysacr02.azurecr.io
    - name: Push the Docker image
      run: docker push barclaysacr02.azurecr.io/deeven01:latest
    
    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: 3.3.1
        
    - name: Login to ACR using HELM
      run: |
        echo $ | helm registry login barclaysacr02.azurecr.io --username barclaysacr02 --password AFnp+BILCUFnV9EuVTr9sxOBt/KqS=yU
        
    - name: Package the helm chart
      run: helm package ./helm/deevenapp01-api
      
    - name: save helm chart to local registry
      run: |
       helm chart save ./deevenapp01-api-0.1.0.tgz barclaysacr02.azurecr.io/charts-deevenapp01-api:latest
       
    - name: Helm chart Push
      run: helm chart push barclaysacr02.azurecr.io/charts-deevenapp01-api:latest
     
      
      
      
      
      
      
      

      





#     - name: Apply AKS Deployment
#       run: kubectl apply -f deployment.yaml
      
#     - name: Apply AKS Deployment
#       run: kubectl apply -f service.yaml
    
    
    
 
 
  
    
